osx_image: xcode10.2
language: objective-c
script:
- set -o pipefail
- xcodebuild -version
- xcodebuild -showsdks
- xcodebuild -workspace Example/AJMessage.xcworkspace -scheme AJMessage-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
