name: Test name top

on: 
 push:
    branches:
    - master
jobs:
  build:
    name: Build
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=12,name=iPhone X']
    steps:
    - name: Checkout
        uses: actions/checkout
    - name: Build and test
        run: xcodebuild clean test -project AJMessage.xcodeproj -scheme AJMessage -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
        destination: ${{ matrix.destination }} 
